# Generated by Django 5.2 on 2025-04-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='No description', max_length=255),
            preserve_default=False,
        ),
    ]
