# Generated by Django 5.2 on 2025-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_transactions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
